apiVersion: apps/v1
kind: Deployment
metadata:
  name: dockersampleconfigdepl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: MedicineStockMicroService
  template:
    metadata:
      labels:
        app: MedicineStockMicroService
    spec:
      containers:
      - name: dockersamplerepos
        image: medicinestockcr1.azurecr.io/dockersamplerepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: dockersampleconfig
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: MedicineStockMicroService